:: Code Generated by Sidekick is for learning and experimentation purposes only.
@echo off
echo Setting AIRFLOW_HOME for this session...
set AIRFLOW_HOME=%cd%

echo Initializing Airflow DB...
airflow db init

echo Creating Airflow admin user...
airflow users create ^
    --username admin ^
    --firstname FIRST ^
    --lastname LAST ^
    --role Admin ^
    --email admin@example.com ^
    --password admin123


pause
